package rs.ac.bg.fon.njt.ppnd.util;

public enum AcademicTitle {
    SARADNIK_U_NASTAVI, ASISTENT, NASTAVNIK_STRANOG_JEZIKA, ASISTENT_SA_DOKTORATOM, DOCENT, VANREDNI_PROF, REDOVNI_PROF, PROF_EMERITUS
}
